/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Päiväaktiivisuus aikaväliltä (oletus 30 päivää). */
        get: operations["list_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kirjautuminen. Onnistuessa asettaa `pdh_session`-cookien ja palauttaa käyttäjän.
         *     Epäonnistuessa 401 ilman erottelua "väärä sähköposti" / "väärä salasana".
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poistaa istuntocookien. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kirjautuneen käyttäjän tiedot. 401, jos istuntoa ei ole tai käyttäjä on poistettu. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cardio-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cardio load aikaväliltä (oletus 30 päivää). */
        get: operations["list_cardio_load"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Harjoitukset uusin ensin, sivutettuna. */
        get: operations["list_exercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yksittäinen harjoitus. */
        get: operations["get_exercise"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Palvelimen ja kantayhteyden tila. 503, jos kanta ei vastaa. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Julkiset asetukset, joita käyttöliittymä tarvitsee ennen kirjautumista. */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/physical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fyysisten tietojen aikasarja (paino, VO2max, leposyke) vanhimmasta uusimpaan. */
        get: operations["list_physical"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/polar/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Polarin paluuohjaus. Tarkistaa `state`-cookien, vaihtaa koodin tokeniin ja tallentaa tilin.
         *     Ohjaa lopuksi osoitteeseen `/settings?polar=connected|denied|error`.
         */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/polar/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Omistaja: aloittaa OAuth2-kierroksen. Ohjaa selaimen Polar Flow:n valtuutussivulle. */
        get: operations["connect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/polar/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Omistaja: poistaa rekisteröinnin Polarista ja tokenin kannasta. */
        delete: operations["disconnect"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/polar/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Omistaja: Polar-tilin tila. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recharge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nightly Recharge -palautuminen aikaväliltä (oletus 30 päivää). */
        get: operations["list_recharge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sleep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yöt aikaväliltä (oletus viimeiset 30 päivää). */
        get: operations["list_sleep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Uni, palautuminen, aktiivisuus ja kuormitus päivittäin yhdellä rivillä. */
        get: operations["daily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboardin yleiskuva: määrät, aikaväli, lajit ja tuoreimmat arvot. */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viikkoyhteenveto: harjoitusmäärät sekä keskimääräinen uni ja palautuminen. */
        get: operations["weekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Omistaja: ajaa synkronoinnin heti ja palauttaa raportin. */
        post: operations["run_now"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Omistaja: viimeisimmät synkronointiajot. */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CardioLoad: {
            /** Format: float */
            cardio_load?: number | null;
            cardio_load_level?: Record<string, never> | null;
            /** Format: float */
            cardio_load_ratio?: number | null;
            /** Format: date */
            date: string;
            /** @description Esim. `PRODUCTIVE`, `MAINTAINING`, `OVERREACHING`. */
            status?: string | null;
            /** Format: float */
            strain?: number | null;
            /** Format: float */
            tolerance?: number | null;
        };
        DailyActivity: {
            /** Format: int32 */
            active_calories?: number | null;
            /** Format: int32 */
            active_duration_s?: number | null;
            /** Format: int32 */
            calories?: number | null;
            /**
             * Format: float
             * @description Päivätavoitteen täyttymisprosentti.
             */
            daily_activity_pct?: number | null;
            /** Format: date */
            date: string;
            /** Format: float */
            distance_from_steps_m?: number | null;
            /** Format: int32 */
            inactive_duration_s?: number | null;
            /** Format: int32 */
            inactivity_alert_count?: number | null;
            /** Format: int32 */
            steps?: number | null;
        };
        DailyWellness: {
            /** Format: int32 */
            active_calories?: number | null;
            /** Format: int32 */
            active_duration_s?: number | null;
            /** Format: float */
            ans_charge?: number | null;
            /** Format: int32 */
            ans_charge_status?: number | null;
            /** Format: int32 */
            calories?: number | null;
            /** Format: float */
            cardio_load?: number | null;
            /** Format: float */
            cardio_load_ratio?: number | null;
            cardio_load_status?: string | null;
            /** Format: float */
            continuity?: number | null;
            /** Format: float */
            daily_activity_pct?: number | null;
            /** Format: date */
            date: string;
            /** Format: int32 */
            deep_sleep_s?: number | null;
            /** Format: float */
            distance_from_steps_m?: number | null;
            /** Format: int32 */
            light_sleep_s?: number | null;
            /** Format: float */
            night_breathing_rate_avg?: number | null;
            /** Format: int32 */
            night_hr_avg?: number | null;
            /** Format: int32 */
            night_hrv_avg_ms?: number | null;
            /** Format: int32 */
            nightly_recharge_status?: number | null;
            /** Format: int32 */
            rem_sleep_s?: number | null;
            /** Format: int32 */
            sleep_charge?: number | null;
            /** Format: int32 */
            sleep_score?: number | null;
            /** Format: int32 */
            sleep_total_s?: number | null;
            /** Format: int32 */
            steps?: number | null;
            /** Format: float */
            strain?: number | null;
            /** Format: float */
            tolerance?: number | null;
            /** Format: int32 */
            total_interruption_s?: number | null;
        };
        /** @description Kaikkien virhevastausten muoto. */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Koneluettava koodi, esim. `unauthorized`, `not_found`. */
            code: string;
            message: string;
        };
        Exercise: {
            /** Format: int32 */
            calories?: number | null;
            /** Format: int32 */
            carbohydrate_percentage?: number | null;
            detailed_sport_info?: string | null;
            device?: string | null;
            /** Format: float */
            distance_m?: number | null;
            /** Format: int32 */
            duration_s: number;
            /** Format: int32 */
            fat_percentage?: number | null;
            has_route: boolean;
            /** @description Polarin sykevyöhykkeet sellaisenaan (`index`, `lower-limit`, `upper-limit`, `in-zone`). */
            heart_rate_zones?: Record<string, never> | null;
            /** Format: int32 */
            hr_avg?: number | null;
            /** Format: int32 */
            hr_max?: number | null;
            id: string;
            /** Format: int32 */
            protein_percentage?: number | null;
            /** Format: int32 */
            running_index?: number | null;
            sport: string;
            /**
             * Format: date-time
             * @description Alkuhetki UTC.
             */
            start_time: string;
            /**
             * Format: date-time
             * @description Alkuhetki paikallisena aikana (kellon aikavyöhyke).
             */
            start_time_local: string;
            /** Format: float */
            training_load?: number | null;
            training_load_pro?: Record<string, never> | null;
            /** Format: date-time */
            upload_time?: string | null;
            /** Format: int32 */
            utc_offset_min: number;
        };
        Health: {
            /** @description `up` tai `down`. */
            database: string;
            /** @description `ok` tai `degraded`. */
            status: string;
            version: string;
        };
        Latest: {
            /** Format: date */
            activity_date?: string | null;
            cardio_load_status?: string | null;
            /** Format: int32 */
            nightly_recharge_status?: number | null;
            /** Format: date */
            recharge_date?: string | null;
            /** Format: int32 */
            resting_heart_rate?: number | null;
            /** Format: date */
            sleep_date?: string | null;
            /** Format: int32 */
            sleep_score?: number | null;
            /** Format: int32 */
            sleep_total_s?: number | null;
            /** Format: int32 */
            steps?: number | null;
            /** Format: int32 */
            vo2_max?: number | null;
            /** Format: float */
            weight_kg?: number | null;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        Meta: {
            /** @description Onko Polar-tunnukset asetettu palvelimelle. */
            polar_configured: boolean;
            /** @description Saako dataa lukea ilman kirjautumista. */
            public_read: boolean;
            version: string;
        };
        NightlyRecharge: {
            /** Format: float */
            ans_charge?: number | null;
            /** Format: int32 */
            ans_charge_status?: number | null;
            /** Format: int32 */
            beat_to_beat_avg_ms?: number | null;
            /** Format: float */
            breathing_rate_avg?: number | null;
            breathing_samples?: Record<string, never> | null;
            /** Format: date */
            date: string;
            /** Format: int32 */
            heart_rate_avg?: number | null;
            /** Format: int32 */
            hrv_avg_ms?: number | null;
            hrv_samples?: Record<string, never> | null;
            /**
             * Format: int32
             * @description 1 = paljon alle tavallisen … 6 = paljon yli tavallisen.
             */
            nightly_recharge_status?: number | null;
        };
        Overview: {
            /** Format: int64 */
            activity_days: number;
            /** Format: int64 */
            exercises: number;
            /**
             * Format: date
             * @description Vanhin ja uusin päivä, jolta on mitä tahansa dataa.
             */
            first_date?: string | null;
            /** Format: date */
            last_date?: string | null;
            /** Format: date-time */
            last_sync_at?: string | null;
            latest: components["schemas"]["Latest"];
            /** @description Onko Polar-tili yhdistetty ja dataa odotettavissa. */
            polar_connected: boolean;
            /** Format: int64 */
            sleep_nights: number;
            /** @description Kannassa esiintyvät lajit suodattimia varten. */
            sports: string[];
        };
        /** @description Sivutettu vastaus. */
        Paged_Exercise: {
            items: {
                /** Format: int32 */
                calories?: number | null;
                /** Format: int32 */
                carbohydrate_percentage?: number | null;
                detailed_sport_info?: string | null;
                device?: string | null;
                /** Format: float */
                distance_m?: number | null;
                /** Format: int32 */
                duration_s: number;
                /** Format: int32 */
                fat_percentage?: number | null;
                has_route: boolean;
                /** @description Polarin sykevyöhykkeet sellaisenaan (`index`, `lower-limit`, `upper-limit`, `in-zone`). */
                heart_rate_zones?: Record<string, never> | null;
                /** Format: int32 */
                hr_avg?: number | null;
                /** Format: int32 */
                hr_max?: number | null;
                id: string;
                /** Format: int32 */
                protein_percentage?: number | null;
                /** Format: int32 */
                running_index?: number | null;
                sport: string;
                /**
                 * Format: date-time
                 * @description Alkuhetki UTC.
                 */
                start_time: string;
                /**
                 * Format: date-time
                 * @description Alkuhetki paikallisena aikana (kellon aikavyöhyke).
                 */
                start_time_local: string;
                /** Format: float */
                training_load?: number | null;
                training_load_pro?: Record<string, never> | null;
                /** Format: date-time */
                upload_time?: string | null;
                /** Format: int32 */
                utc_offset_min: number;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            per_page: number;
            /** Format: int64 */
            total: number;
        };
        PhysicalInfo: {
            /** Format: int32 */
            aerobic_threshold?: number | null;
            /** Format: int32 */
            anaerobic_threshold?: number | null;
            /** Format: date */
            date: string;
            /** Format: float */
            height_cm?: number | null;
            /** Format: int32 */
            maximum_heart_rate?: number | null;
            /** Format: date-time */
            modified_at: string;
            /** Format: int32 */
            resting_heart_rate?: number | null;
            /** Format: int32 */
            sleep_goal_s?: number | null;
            /** Format: int32 */
            vo2_max?: number | null;
            /** Format: float */
            weight_kg?: number | null;
            weight_source?: string | null;
        };
        PolarStatus: {
            /** @description Onko Polar-tunnukset asetettu palvelimelle. */
            configured: boolean;
            connected: boolean;
            /** Format: date-time */
            last_sync_at?: string | null;
            /** Format: int64 */
            polar_user_id?: number | null;
            /** Format: date-time */
            registered_at?: string | null;
        };
        /**
         * @description Käyttäjän rooli. `Owner` saa yhdistää Polar-tilin ja käynnistää
         *     synkronoinnin; `Viewer` näkee vain datan.
         * @enum {string}
         */
        Role: "owner" | "viewer";
        SleepNight: {
            /** Format: float */
            continuity?: number | null;
            /** Format: int32 */
            continuity_class?: number | null;
            /** Format: date */
            date: string;
            /** Format: int32 */
            deep_sleep_s?: number | null;
            /** Format: float */
            group_duration_score?: number | null;
            /** Format: float */
            group_regeneration_score?: number | null;
            /** Format: float */
            group_solidity_score?: number | null;
            /** @description Syke 5 min välein yön aikana. */
            heart_rate_samples?: Record<string, never> | null;
            /** @description Univaiheet aikaleimoittain, esim. `{"23:12": 1, "23:40": 2}`. */
            hypnogram?: Record<string, never> | null;
            /** Format: int32 */
            light_sleep_s?: number | null;
            /** Format: int32 */
            long_interruption_s?: number | null;
            /** Format: int32 */
            rem_sleep_s?: number | null;
            /** Format: int32 */
            short_interruption_s?: number | null;
            /** Format: int32 */
            sleep_charge?: number | null;
            /** Format: int32 */
            sleep_cycles?: number | null;
            /** Format: date-time */
            sleep_end_time: string;
            /** Format: int32 */
            sleep_goal_s?: number | null;
            /** Format: int32 */
            sleep_rating?: number | null;
            /** Format: int32 */
            sleep_score?: number | null;
            /** Format: date-time */
            sleep_start_time: string;
            /** Format: int32 */
            total_interruption_s?: number | null;
            /** Format: int32 */
            unrecognized_sleep_s?: number | null;
        };
        SyncCounts: {
            /** Format: int32 */
            cardio_load: number;
            /** Format: int32 */
            daily_activity: number;
            /** Format: int32 */
            exercises: number;
            /** Format: int32 */
            nightly_recharge: number;
            /** Format: int32 */
            physical_info: number;
            /**
             * Format: int32
             * @description Alkiot, joita ei voitu jäsentää tai tallentaa.
             */
            skipped: number;
            /** Format: int32 */
            sleep_nights: number;
        };
        SyncReport: {
            counts: components["schemas"]["SyncCounts"];
            errors: string[];
            /** Format: date-time */
            finished_at: string;
            /** Format: int64 */
            run_id: number;
            /** Format: date-time */
            started_at: string;
            /** @description `ok`, `partial` tai `failed`. */
            status: string;
            trigger: string;
        };
        SyncRunRecord: {
            /** @description Upsertattujen rivien määrät datatyypeittäin. */
            counts: Record<string, never>;
            error?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            started_at: string;
            status: string;
            trigger: string;
        };
        /**
         * @description Sovelluskäyttäjä ilman salasanatiivistettä. Tämä on se muoto, joka
         *     palautetaan rajapinnasta.
         */
        User: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: uuid */
            id: string;
            role: components["schemas"]["Role"];
        };
        WeeklySummary: {
            /** Format: double */
            avg_hr?: number | null;
            /** Format: double */
            avg_night_hrv_ms?: number | null;
            /** Format: double */
            avg_recharge_status?: number | null;
            /** Format: double */
            avg_sleep_score?: number | null;
            /** Format: double */
            avg_sleep_total_s?: number | null;
            /** Format: int64 */
            exercise_count: number;
            /** Format: int32 */
            max_hr?: number | null;
            /** Format: int64 */
            nights_with_sleep: number;
            /** Format: int64 */
            total_calories?: number | null;
            /** Format: float */
            total_distance_m?: number | null;
            /** Format: int64 */
            total_duration_s: number;
            /** Format: int64 */
            total_steps?: number | null;
            /** Format: float */
            total_training_load?: number | null;
            /**
             * Format: date
             * @description Viikon maanantai.
             */
            week_start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activity: {
        parameters: {
            query?: {
                /** @description Alkupäivä (YYYY-MM-DD), mukaan lukien. */
                from?: string;
                /** @description Loppupäivä (YYYY-MM-DD), mukaan lukien. Oletus tänään. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyActivity"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_cardio_load: {
        parameters: {
            query?: {
                /** @description Alkupäivä (YYYY-MM-DD), mukaan lukien. */
                from?: string;
                /** @description Loppupäivä (YYYY-MM-DD), mukaan lukien. Oletus tänään. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardioLoad"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_exercises: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                /** @description Lajisuodatin, esim. `RUNNING`. */
                sport?: string;
                /** @description Sivunumero alkaen 1:stä. */
                page?: number;
                /** @description Rivejä per sivu (1–200, oletus 50). */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_Exercise"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_exercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Polarin harjoitus-id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_physical: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhysicalInfo"][];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                /** @description Polar asettaa tämän, jos käyttäjä kieltäytyy. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect asetussivulle */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    connect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Polariin */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolarStatus"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_recharge: {
        parameters: {
            query?: {
                /** @description Alkupäivä (YYYY-MM-DD), mukaan lukien. */
                from?: string;
                /** @description Loppupäivä (YYYY-MM-DD), mukaan lukien. Oletus tänään. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NightlyRecharge"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sleep: {
        parameters: {
            query?: {
                /** @description Alkupäivä (YYYY-MM-DD), mukaan lukien. */
                from?: string;
                /** @description Loppupäivä (YYYY-MM-DD), mukaan lukien. Oletus tänään. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleepNight"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    daily: {
        parameters: {
            query?: {
                /** @description Alkupäivä (YYYY-MM-DD), mukaan lukien. */
                from?: string;
                /** @description Loppupäivä (YYYY-MM-DD), mukaan lukien. Oletus tänään. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyWellness"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    weekly: {
        parameters: {
            query?: {
                /** @description Montako viimeistä viikkoa (1–104, oletus 12). */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummary"][];
                };
            };
        };
    };
    run_now: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncReport"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                /** @description Montako viimeisintä ajoa (1-200, oletus 20). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunRecord"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
